name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Используем локальный runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server via SSH
        run: |
            cd /home/bitrix/www/local/components
            git pull origin main
